{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "935f33a3-b616-401f-80a4-a95e2c775f06",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sqlite3\n",
    "import pandas as pd\n",
    "\n",
    "\n",
    "# =========================\n",
    "# PLANETS DATABASE\n",
    "# =========================\n",
    "\n",
    "def step1():\n",
    "    conn1 = sqlite3.connect('planets.db')\n",
    "    df = pd.read_sql(\n",
    "        \"\"\"\n",
    "        SELECT *\n",
    "        FROM planets\n",
    "        WHERE number_of_moons = 0\n",
    "        \"\"\",\n",
    "        conn1\n",
    "    )\n",
    "    conn1.close()\n",
    "    return df\n",
    "\n",
    "\n",
    "def step2():\n",
    "    conn1 = sqlite3.connect('planets.db')\n",
    "    df = pd.read_sql(\n",
    "        \"\"\"\n",
    "        SELECT name, mass\n",
    "        FROM planets\n",
    "        WHERE LENGTH(name) = 7\n",
    "        \"\"\",\n",
    "        conn1\n",
    "    )\n",
    "    conn1.close()\n",
    "    return df\n",
    "\n",
    "\n",
    "def step3():\n",
    "    conn1 = sqlite3.connect('planets.db')\n",
    "    df = pd.read_sql(\n",
    "        \"\"\"\n",
    "        SELECT name, mass\n",
    "        FROM planets\n",
    "        WHERE mass <= 1.00\n",
    "        \"\"\",\n",
    "        conn1\n",
    "    )\n",
    "    conn1.close()\n",
    "    return df\n",
    "\n",
    "\n",
    "def step4():\n",
    "    conn1 = sqlite3.connect('planets.db')\n",
    "    df = pd.read_sql(\n",
    "        \"\"\"\n",
    "        SELECT *\n",
    "        FROM planets\n",
    "        WHERE number_of_moons >= 1\n",
    "        AND mass < 1.00\n",
    "        \"\"\",\n",
    "        conn1\n",
    "    )\n",
    "    conn1.close()\n",
    "    return df\n",
    "\n",
    "\n",
    "def step5():\n",
    "    conn1 = sqlite3.connect('planets.db')\n",
    "    df = pd.read_sql(\n",
    "        \"\"\"\n",
    "        SELECT name, color\n",
    "        FROM planets\n",
    "        WHERE color LIKE '%blue%'\n",
    "        \"\"\",\n",
    "        conn1\n",
    "    )\n",
    "    conn1.close()\n",
    "    return df\n",
    "\n",
    "\n",
    "# =========================\n",
    "# DOGS DATABASE\n",
    "# =========================\n",
    "\n",
    "def step6():\n",
    "    conn2 = sqlite3.connect('dogs.db')\n",
    "    df = pd.read_sql(\n",
    "        \"\"\"\n",
    "        SELECT name, age, breed\n",
    "        FROM dogs\n",
    "        WHERE hungry = 1\n",
    "        ORDER BY age ASC\n",
    "        \"\"\",\n",
    "        conn2\n",
    "    )\n",
    "    conn2.close()\n",
    "    return df\n",
    "\n",
    "\n",
    "def step7():\n",
    "    conn2 = sqlite3.connect('dogs.db')\n",
    "    df = pd.read_sql(\n",
    "        \"\"\"\n",
    "        SELECT name, age, hungry\n",
    "        FROM dogs\n",
    "        WHERE hungry = 1\n",
    "        AND age BETWEEN 2 AND 7\n",
    "        ORDER BY name ASC\n",
    "        \"\"\",\n",
    "        conn2\n",
    "    )\n",
    "    conn2.close()\n",
    "    return df\n",
    "\n",
    "\n",
    "def step8():\n",
    "    conn2 = sqlite3.connect('dogs.db')\n",
    "    df = pd.read_sql(\n",
    "        \"\"\"\n",
    "        SELECT name, age, breed\n",
    "        FROM dogs\n",
    "        ORDER BY age DESC, breed ASC\n",
    "        LIMIT 4\n",
    "        \"\"\",\n",
    "        conn2\n",
    "    )\n",
    "    conn2.close()\n",
    "    return df\n",
    "\n",
    "\n",
    "# =========================\n",
    "# BABE RUTH DATABASE\n",
    "# =========================\n",
    "\n",
    "def step9():\n",
    "    conn3 = sqlite3.connect('babe_ruth.db')\n",
    "    df = pd.read_sql(\n",
    "        \"\"\"\n",
    "        SELECT COUNT(DISTINCT year) AS years_played\n",
    "        FROM babe_ruth_stats\n",
    "        \"\"\",\n",
    "        conn3\n",
    "    )\n",
    "    conn3.close()\n",
    "    return df\n",
    "\n",
    "\n",
    "def step10():\n",
    "    conn3 = sqlite3.connect('babe_ruth.db')\n",
    "    df = pd.read_sql(\n",
    "        \"\"\"\n",
    "        SELECT SUM(HR) AS Homerun_hits\n",
    "        FROM babe_ruth_stats\n",
    "        \"\"\",\n",
    "        conn3\n",
    "    )\n",
    "    conn3.close()\n",
    "    return df\n",
    "\n",
    "\n",
    "def step11():\n",
    "    conn3 = sqlite3.connect('babe_ruth.db')\n",
    "    df = pd.read_sql(\n",
    "        \"\"\"\n",
    "        SELECT team, COUNT(DISTINCT year) AS number_years\n",
    "        FROM babe_ruth_stats\n",
    "        GROUP BY team\n",
    "        \"\"\",\n",
    "        conn3\n",
    "    )\n",
    "    conn3.close()\n",
    "    return df\n",
    "\n",
    "\n",
    "def step12():\n",
    "    conn3 = sqlite3.connect('babe_ruth.db')\n",
    "    df = pd.read_sql(\n",
    "        \"\"\"\n",
    "        SELECT team, AVG(at_bats) AS average_at_bats\n",
    "        FROM babe_ruth_stats\n",
    "        GROUP BY team\n",
    "        HAVING AVG(at_bats) > 200\n",
    "        \"\"\",\n",
    "        conn3\n",
    "    )\n",
    "    conn3.close()\n",
    "    return df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e7d35c90-7e81-46f9-9615-3869386dc6c6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
